cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: null
    #rbriggs:
    #  email: rbriggs@gmail.com
    #  name: Rebecca Briggs
    #  password: null
preauthorized:
  emails:
    #melsby@gmail.com
